Change media query
PandaCrab/testProjects pull request #2
Opened 2022-02-22 17:55 UTC by PandaCrab

2022-02-22 22:25 UTC, mike-gusiev requested changes

2022-02-22 22:25 UTC, mike-gusiev commented on src/App/App.js
>      <>
винеси App.js в src/App.js

2022-02-22 22:25 UTC, mike-gusiev commented on src/App/App.js
>          <ShoppingBasket>cart</ShoppingBasket>
мобільна верстка неюзабельна. зроби нормальну респонсів верстку для вузьких екранів. щоб цим можна користуватися

2022-02-22 22:25 UTC, mike-gusiev commented on src/Components/Forms/BillingInfo.js
>  const emailRegex = /^(("[\w-\s]+")|([\w-]+(?:\.[\w-]+)*)|("[\w-\s]+")([\w-]+(?:\.[\w-]+)*))(@((?:[\w-]+\.)*\w[\w-]{0,66})\.([a-z]{2,6}(?:\.[a-z]{2})?)$)|(@\[?((25[0-5]\.|2[0-4][0-9]\.|1[0-9]{2}\.|[0-
повинось усю логіку валидіацій в окремі функції в src/helpers.js

2022-02-22 22:25 UTC, mike-gusiev commented on src/Styled/App/AppStyles.js
>    margin: auto;
позбудься зайвих папок. якщо в папці лежить один файл - то не треба для нього створювати папку

2022-03-29 08:42 UTC, mike-gusiev requested changes

2022-03-29 08:42 UTC, mike-gusiev commented on src/App.js
>  function App() {
використовуй коротку форму es6 функцій без return, там де це можливо

2022-03-29 08:42 UTC, mike-gusiev commented on src/App.js
> +} from './Components/Index';
можно без Index це імпортити

2022-03-29 08:42 UTC, mike-gusiev commented on src/Components/Forms/Payment.js
>          e.preventDefault()
не використовуй одно або двобуквені назви змінних. усі назви змінних мають бути осмисленими

2022-03-29 08:42 UTC, mike-gusiev commented on src/Components/OrderPlate.js
> +    //const [order, setOrder] = useState({})
не залишай закоментований код в репозиторії

2022-03-29 08:42 UTC, mike-gusiev commented on src/Components/OrderPlate.js
> +import { BsBasket3 } from 'react-icons/bs'
крапку з комою не поставив

2022-03-29 08:42 UTC, mike-gusiev commented on src/Components/OrderPlate.js
> +
зайві переноси рядка. максимум один перенос має бути. і крапку з комою не забувай ставити

2022-03-29 08:42 UTC, mike-gusiev commented on src/Components/OrderPlate.js
> +};
перед відправкою пул реквеста на рев'ю переглядай файли свого пул реквесту на гітхабі. і виправиш все що помітиш самостійно, до того як мені відправляти на рев'ю.

якщо бачиш таку іконку, значить у цього файлу не вистачає переносу рядка в кінці.

2022-03-29 08:42 UTC, mike-gusiev commented on src/Styled/FormStyle.js
> +// `
повидаляй закоментований код

2022-03-29 08:42 UTC, mike-gusiev commented on src/Styled/OrderPlateStyles.js
> +
зайви переноси рядків. немає крапки з комою після закриття блоку стилізації

2022-03-29 08:42 UTC, mike-gusiev commented on src/helpers.js
> +    export const FindFormErrors = (info) => {
зайвий відступ зліва у цього блока

2022-03-29 09:59 UTC, PandaCrab commented on src/App.js
>  function App() {
Там ругається, не вставляє потім елемент

2022-03-29 10:00 UTC, PandaCrab commented on src/App.js
> +} from './Components/Index';
Видає помилку коли видаляю index

2022-03-29 10:03 UTC, merged