Add ruting, redux and redux-saga, Formik
PandaCrab/testProjects pull request #3
Opened 2022-03-31 07:53 UTC by PandaCrab

2022-04-07 11:59 UTC, mike-gusiev requested changes

2022-04-07 11:59 UTC, mike-gusiev commented on src/App.js
> +import { OrderPlate } from './Components/Index';
Index зайвий. не треба його вказувати

2022-04-07 11:59 UTC, mike-gusiev commented on src/App.js
зайвий перенос рядка. більше одного переносу не роби

2022-04-07 11:59 UTC, mike-gusiev commented on src/App.js
>  function App() {
використовуй коротку форму es6 функцій без return, там де це можливо

2022-04-07 11:59 UTC, mike-gusiev commented on src/App.js
зайвий перенос рядка

2022-04-07 11:59 UTC, mike-gusiev commented on src/Components/Forms/SuccessBuying.js
> +import React from "react";
одинарні кавички

2022-04-07 11:59 UTC, mike-gusiev commented on src/Components/Forms/SuccessBuying.js
> +    return (
зайвий return, використовую коротку форму

2022-04-07 11:59 UTC, mike-gusiev commented on src/Components/OrderPlate/Stuff.js
> +import { StuffItems } from './StuffItems';
погрупуй імпорти. спочатку будуть іти імпорти бібліотек, потім відступ, потім імпорти компонентів, потім відступ, потім імпорт всього іншого

2022-04-07 11:59 UTC, mike-gusiev commented on src/Components/OrderPlate/Stuff.js
> +        const dispatch = useDispatch();
зайві відступи зліва

2022-04-07 11:59 UTC, mike-gusiev commented on src/Components/OrderPlate/StuffItems.js
> +}
перед відправкою пул реквеста на рев'ю переглядай файли свого пул реквесту на гітхабі. і виправиш все що помітиш самостійно, до того як мені відправляти на рев'ю.

якщо бачиш таку іконку, значить у цього файлу не вистачає переносу рядка в кінці.

2022-04-07 11:59 UTC, mike-gusiev commented on src/Redux/modules/dataReducer.js
> +export const REQUEST_DATA = 'data/REQUEST_DATA';
структура редаксу трохи неправильна. позбудься папки modules. і створи папку src/redux/ducks. і туди в окремі файли помісти усі екшени/редюсери/саги і тд одним файлом. все що відноситься до одного duck - має бути в одному файлі:
https://github.com/erikras/ducks-modular-redux

2022-04-07 19:04 UTC, PandaCrab commented on src/App.js
> +import { OrderPlate } from './Components/Index';
Не можу, ругаеється

2022-04-07 19:06 UTC, PandaCrab commented on src/Components/Forms/SuccessBuying.js
> +    return (
Реакт компонент, без нього не працює

2022-04-08 09:28 UTC, mike-gusiev requested changes

2022-04-08 09:28 UTC, mike-gusiev commented on src/Components/Forms/BillingInfo.js
>  import {
роби в один рядок такі іморти. не має сенсу так робити:
`import { Form, Col, Row } from 'react-bootstrap';`

2022-04-08 09:28 UTC, mike-gusiev commented on src/Components/Forms/SuccessBuying.js
> +    return (
працює:
```
export const SuccessBuying = () => (
    <>
        <Info>
            <h1>Buying is success! huray!</h1>
        </Info>
    </>
);
```

2022-04-08 09:28 UTC, mike-gusiev commented on src/Components/Loader.js
> +    return (
зроби коротку форму тут і усіх інших місцях

2022-04-08 09:28 UTC, mike-gusiev commented on src/Redux/ducks/data.js
> +import { takeEvery,call,select } from "@redux-saga/core/effects";
одинарні кавички

2022-04-08 09:28 UTC, mike-gusiev commented on src/Redux/ducks/data.js
> +    return {
зроби коротку форму без return

2022-04-08 09:28 UTC, mike-gusiev commented on src/Redux/ducks/data.js
> +    return fetch('https://624d3b89d71863d7a814e6c2.mockapi.io/shopping/info', {
в редаксі не має бути жодної логіки з API запитами. повинось все в src/api.js. і переведи на ES6

2022-04-08 09:28 UTC, mike-gusiev commented on src/Redux/ducks/stuff.js
> +        return {
зайві відступи зліва. переведи на es6 функції

2022-04-08 09:28 UTC, mike-gusiev commented on src/Redux/rootReducer.js
> +export const rootReducer = combineReducers({
перенеси це в store.js. позбудься цього файлу

2022-04-08 09:28 UTC, mike-gusiev commented on src/Redux/store.js
> +import { compose, createStore, applyMiddleware } from "@reduxjs/toolkit";
усі назви папок мають бути з маленької букви. використовуй camelCase всюди

2022-04-08 09:28 UTC, mike-gusiev commented on src/Redux/store.js
> +import { stuffWatcher} from "./ducks/stuff";
одинарні кавички

2022-04-08 09:28 UTC, mike-gusiev commented on src/Styles/AppStyles.js
> +  background-color: #ff1876;
колір не виніс у змінні

2022-04-09 11:44 UTC, mike-gusiev requested changes

2022-04-09 11:44 UTC, mike-gusiev commented on package.json
>    "version": "0.1.0",
не хоче білдитися:
https://take.ms/fN8Ds

2022-04-09 11:44 UTC, mike-gusiev commented on src/App.js
> +import { OrderPlate } from './components/Index';
спочатку йде імпорт бібліотек, а вже потім імпорти файлів

2022-04-09 11:44 UTC, mike-gusiev commented on src/Components/Forms/SuccessBuying.js
> +const SuccessBuying = () =>
обгорни круглими скобками jsx розмітку

2022-04-09 11:44 UTC, mike-gusiev commented on src/Redux/ducks/stuff.js
> +    yield takeEvery(
- в один рядок запиши
- крапка з комою

2022-04-09 11:44 UTC, mike-gusiev commented on src/api.js
> +    fetch('https://624d3b89d71863d7a814e6c2.mockapi.io/shopping/info', {
- винеси урл в константу. і цю константу використовуй в обох запитах
- fetch також винеси в окрему функцію і цю функцію викотристовуй в обох місцях. щоб потім можна було легко замінити fetch на будь яку іншу бібліотеку

2022-04-09 11:44 UTC, mike-gusiev commented on src/helpers.js
>      };
після if не ставиться крапка з комою

2022-04-11 11:03 UTC, merged